### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Genius8**
This is a project that consists of building a web page using images as a background and adding gradients to elements.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Genius8 
### Good job you have done so far :clap: However, you have a few changes to implement before your project could be approved.
- Reconfigure stickler to help with the linting issues, [check this guide](https://github.com/microverseinc/linters-config/tree/master/css)
- Validate your html code using [this online tool](https://validator.w3.org/#validate_by_upload)
validate
- Remove the horizontal scroll bar
- Redesign the footer to match the original website 
footer
- On the navigation, redesign it to match the original website as well
nav
- Add these elements as text not as an image on the hero image
text
### Make these changes and resubmit for another review. Good luck.
- For assistance, contact me on slack @iamraymond
- Happy coding!

**Comment by Genius8** [comment]
I have implimented the changes you sugguested, please review my changes.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Genius8 
### You have done well and for also implementing changes from the previous reviews. However, you still some issues to solve.
- The logo is not aligned with the rest of the navigation items, make it uniform
nav
- The footer still not looking great as expected, you can use flex or grid layouts to set two columns and put the list items inside the columns
footer
### Make these changes and resubmit for another code review. Good luck.
- Happy coding!
- Contact: Slack @iamraymond

**Review by rOluochKe — APPROVED** [review]
Hello @Genius8 
### Well done :clap: for also implementing changes from previous reviews. Your project looks good and I approve of it. Congratulations :boom: :100:
### You can merge and complete a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
